### ISSUE TITLE
Probability correction function does not seem to be correct

### ISSUE THREAD

**Issue by hari-kk** [pxiangwu/PLC#4]
In the probability correction algorithm, the generated labels should be multinoimally distributed among all the aviable labels. However according to the code given, it will just be 0 or 1

The issue come because the code 
https://github.com/pxiangwu/PLC/blob/8c2bcfd25e538fdcdb637a820ac340e9ee084e59/utils.py#L336-L341

will result in a scalar `top_probs`. Hence the code to generate new labels  
https://github.com/pxiangwu/PLC/blob/8c2bcfd25e538fdcdb637a820ac340e9ee084e59/utils.py#L349-L353 will result in `new_label` being just 0 or 1. 

Moreover the normalization here https://github.com/pxiangwu/PLC/blob/8c2bcfd25e538fdcdb637a820ac340e9ee084e59/utils.py#L350 will result in `top_probs` always being `1.0` thereby invalidating the whole idea of sampling from distribution.

Is this intended behavior?

**Comment by pingqingsheng** [comment]
`cur_prob_distri` here has shape  BatchSize x NumClasses.  So `top_probs` has shape NumClasses, which is the simplex we use to generate the new labels.  Let me know if you have more questions.

**Comment by pingqingsheng** [comment]
`cur_prob_distri` here has shape  BatchSize x NumClasses.  So `top_probs` has shape NumClasses, which is the simplex we use to generate the new labels.  Let me know if you have more questions.

**Comment by pingqingsheng** [comment]
"lrt_correction" and "prob_correction" are actually the same. We didn't clean our code and due to some historical reason there are two versions of such implementations, which is what we present in our paper.  In other words, in the current version both functions achieve the same thing.  We will clean it and update the code later.

We once wanted to try "prob_correction" which stochastically flip labels according to confidence, but it doesn't help a lot. You can try that yourself by changing the line "top_k_idx = np.argsort(cur_prob_distri)[-1:] " to "top_k_idx = np.argsort(cur_prob_distri)".
